### ISSUE TITLE
Text appears in the wrong place on Anilist, overlaps with regular site info

### ISSUE THREAD

**Issue by IroConOx** [laxyapahuja/nyaamal#5]
![image](https://user-images.githubusercontent.com/54962938/155197605-78a519b9-a54e-494d-a528-06d876b94227.png)
Text which should appear to the right appears on the left, overlapping the anime info.
I am using Opera GX, and I also have the MAL-sync extension installed.

**Comment by laxyapahuja** [comment]
investigating into this problem. thanks for bringing it up

**Comment by sheldor1510** [comment]
fixed the issue. @rustokomuska re-clone the extension and try it out again.

commit: c223d63510504bfe907d11bbc6794ed2bd217886
